export type PlanFeatureRow = {
  key: string;
  included: boolean;
  detailKey?: string;
  detailParams?: Record<string, string | number>;
};

export const PLAN_FEATURES: Record<string, PlanFeatureRow[]> = {
  FREE: [
    { key: 'trades', included: true, detailKey: 'tradesCount', detailParams: { count: 100 } },
    { key: 'brokerAccount', included: true, detailKey: 'accountsCount', detailParams: { count: 1 } },
    { key: 'sync', included: true, detailKey: 'syncMonthly' },
    { key: 'csvImport', included: true },
    { key: 'journal', included: true },
    { key: 'basicMetrics', included: true },
    { key: 'badges', included: true },
    { key: 'csvExport', included: false },
    { key: 'alerts', included: false },
    { key: 'aiCoach', included: false },
    { key: 'reports', included: false },
    { key: 'backtesting', included: false },
    { key: 'tradeReplay', included: false },
  ],
  STARTER: [
    { key: 'trades', included: true, detailKey: 'tradesCount', detailParams: { count: 1500 } },
    { key: 'brokerAccounts', included: true, detailKey: 'accountsCount', detailParams: { count: 2 } },
    { key: 'sync', included: true, detailKey: 'syncWeekly' },
    { key: 'csvImportExport', included: true },
    { key: 'journal', included: true, detailKey: 'withCalendar' },
    { key: 'basicMetrics', included: true },
    { key: 'badges', included: true },
    { key: 'aiCoach', included: true, detailKey: 'aiMsgPerDay', detailParams: { count: 5 } },
    { key: 'alerts', included: true, detailKey: 'priceAlertsCount', detailParams: { count: 5 } },
    { key: 'reports', included: true, detailKey: 'reportsPerMonth', detailParams: { count: 3 } },
    { key: 'marketFeed', included: true, detailKey: 'sourcesCount', detailParams: { count: 1 } },
    { key: 'economicCalendar', included: true },
    { key: 'backtesting', included: false },
    { key: 'tradeReplay', included: false },
  ],
  PRO: [
    { key: 'trades', included: true, detailKey: 'tradesCount', detailParams: { count: 15000 } },
    { key: 'brokerAccounts', included: true, detailKey: 'accountsCount', detailParams: { count: 5 } },
    { key: 'sync', included: true, detailKey: 'syncDaily' },
    { key: 'csvImportExport', included: true },
    { key: 'journal', included: true, detailKey: 'withCalendar' },
    { key: 'advancedMetrics', included: true, detailKey: 'sharpeVar' },
    { key: 'liveWebSocket', included: true },
    { key: 'aiCoach', included: true, detailKey: 'aiMsgPerDay', detailParams: { count: 30 } },
    { key: 'alerts', included: true, detailKey: 'alertsCount', detailParams: { count: 25 } },
    { key: 'reports', included: true, detailKey: 'reportsProDetail' },
    { key: 'backtesting', included: true, detailKey: 'backtestSessions', detailParams: { count: 3 } },
    { key: 'tradeReplay', included: true },
    { key: 'taxPreview', included: true },
    { key: 'publicProfile', included: true },
  ],
  ELITE: [
    { key: 'trades', included: true, detailKey: 'unlimited' },
    { key: 'brokerAccounts', included: true, detailKey: 'unlimited' },
    { key: 'sync', included: true, detailKey: 'syncRealtime' },
    { key: 'everything', included: true, detailKey: 'allFeaturesPro' },
    { key: 'aiCoach', included: true, detailKey: 'aiMsgPerDay', detailParams: { count: 150 } },
    { key: 'alerts', included: true, detailKey: 'alertsUnlimitedAll' },
    { key: 'reports', included: true, detailKey: 'reportsEliteDetail' },
    { key: 'backtesting', included: true, detailKey: 'backtestUnlimited' },
    { key: 'fullTaxReport', included: true, detailKey: 'taxJurisdictions', detailParams: { count: 14 } },
    { key: 'dedicatedSupport', included: true },
    { key: 'customRss', included: true },
  ],
  TEAM: [
    { key: 'everything', included: true, detailKey: 'allFeaturesElite' },
    { key: 'mentorInstance', included: true, detailKey: 'brandedAcademy' },
    { key: 'students', included: true, detailKey: 'studentsMax', detailParams: { count: 20 } },
    { key: 'mentorDashboard', included: true, detailKey: 'mentorScope' },
    { key: 'studentBoost', included: true, detailKey: 'studentBoostDesc' },
    { key: 'inviteCode', included: true, detailKey: 'publicJoin' },
    { key: 'privacyControls', included: true, detailKey: 'studentToggles' },
    { key: 'dedicatedSupport', included: true },
  ],
};
