import React from 'react';
import { RefreshCw, Loader2, AlertCircle } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { useBriefing, useGenerateBriefing } from '@/hooks/useBriefing';

const formatInline = (text: string): string =>
  text
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>');

/** Strip the backend-injected English disclaimer so the page-level i18n disclaimer is used */
const DISCLAIMER_PATTERNS = [
  /\*?This analysis is based on your historical.*?responsibility\.\*?/gi,
  /\*?This is based on your historical.*?responsibility\.\*?/gi,
  /\*?Based on your historical data\..*?advice\.\*?/gi,
  /\*?Not investment advice\.\*?/gi,
];

/** Markdown renderer — handles headings, **bold**, *italic*, bullets, and cleans raw artifacts */
const SimpleMarkdown: React.FC<{ text: string }> = ({ text }) => {
  let cleaned = text
    .replace(/^---+\s*$/gm, '')
    .trim();

  // Strip disclaimer lines (injected by DisclaimerInjector or generated by LLM)
  for (const pattern of DISCLAIMER_PATTERNS) {
    cleaned = cleaned.replace(pattern, '');
  }
  cleaned = cleaned.trim();

  return (
    <div className="space-y-1.5 text-sm text-foreground">
      {cleaned.split('\n').map((line, i) => {
        const trimmed = line.trim();

        if (trimmed.startsWith('## ')) {
          return (
            <h4 key={i} className="text-xs font-bold uppercase tracking-wider text-muted-foreground pt-2 first:pt-0">
              {trimmed.replace(/^#+\s*/, '')}
            </h4>
          );
        }
        if (trimmed.startsWith('# ')) {
          return (
            <h3 key={i} className="text-sm font-bold text-foreground pt-2 first:pt-0">
              {trimmed.replace(/^#+\s*/, '')}
            </h3>
          );
        }

        if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
          const content = trimmed.slice(2);
          return (
            <div key={i} className="flex gap-2">
              <span className="text-muted-foreground mt-0.5 flex-shrink-0">•</span>
              <span dangerouslySetInnerHTML={{ __html: formatInline(content) }} />
            </div>
          );
        }

        if (!trimmed) return <div key={i} className="h-1" />;

        return (
          <p key={i} dangerouslySetInnerHTML={{ __html: formatInline(trimmed) }} />
        );
      })}
    </div>
  );
};

interface BriefingCardProps {
  accountId?: string;
}

const BriefingCard: React.FC<BriefingCardProps> = ({ accountId }) => {
  const { t } = useTranslation();
  const { data: briefing, isLoading } = useBriefing(accountId);
  const { mutate: generate, isPending: isGenerating } = useGenerateBriefing(accountId);

  if (isLoading) {
    return (
      <div className="space-y-3">
        <Skeleton className="h-4 w-full" />
        <Skeleton className="h-4 w-5/6" />
        <Skeleton className="h-4 w-4/6" />
      </div>
    );
  }

  return (
    <div className="space-y-3">
      {/* Header — date + generate button */}
      <div className="flex items-center justify-between">
        {briefing ? (
          <span className="text-xs text-muted-foreground font-mono tabular-nums">
            {new Date(briefing.briefingDate).toLocaleDateString()}
          </span>
        ) : (
          <span />
        )}
        <Button
          variant="ghost"
          size="sm"
          onClick={() => generate()}
          disabled={isGenerating}
          className="h-7 text-xs gap-1.5"
        >
          {isGenerating ? (
            <Loader2 className="h-3.5 w-3.5 animate-spin" />
          ) : (
            <RefreshCw className="h-3.5 w-3.5" />
          )}
          {briefing ? t('ai.regenerate') : t('ai.generateBtn')}
        </Button>
      </div>

      {/* Content */}
      {briefing ? (
        <div className="space-y-3">
          <SimpleMarkdown text={briefing.content} />
          {briefing.warnings && (
            <div className="flex gap-2 p-3 bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-lg">
              <AlertCircle className="h-4 w-4 text-amber-600 dark:text-amber-400 flex-shrink-0 mt-0.5" />
              <div className="text-xs text-amber-800 dark:text-amber-200">
                <strong>Warnings:</strong> {briefing.warnings}
              </div>
            </div>
          )}
        </div>
      ) : (
        <div className="text-center py-4">
          <p className="text-xs text-muted-foreground">
            {t('ai.briefingEmpty')}
          </p>
        </div>
      )}
    </div>
  );
};

export default BriefingCard;
