import React from 'react';
import { RefreshCw, Loader2, AlertCircle, ArrowRight, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { useBriefing, useGenerateBriefing } from '@/hooks/useBriefing';
import { cn } from '@/lib/utils';

const formatInline = (text: string): string =>
  text
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>');

/** Strip the backend-injected English disclaimer so the page-level i18n disclaimer is used */
const DISCLAIMER_PATTERNS = [
  /\*?This analysis is based on your historical.*?responsibility\.\*?/gi,
  /\*?This is based on your historical.*?responsibility\.\*?/gi,
  /\*?Based on your historical data\..*?advice\.\*?/gi,
  /\*?Not investment advice\.\*?/gi,
];

/** Markdown renderer — handles headings, **bold**, *italic*, bullets, and cleans raw artifacts */
const SimpleMarkdown: React.FC<{ text: string }> = ({ text }) => {
  let cleaned = text
    .replace(/^---+\s*$/gm, '')
    .trim();

  // Strip disclaimer lines (injected by DisclaimerInjector or generated by LLM)
  for (const pattern of DISCLAIMER_PATTERNS) {
    cleaned = cleaned.replace(pattern, '');
  }
  cleaned = cleaned.trim();

  return (
    <div className="space-y-1.5 text-sm text-foreground">
      {cleaned.split('\n').map((line, i) => {
        const trimmed = line.trim();

        if (trimmed.startsWith('## ')) {
          return (
            <h4 key={i} className="text-xs font-bold uppercase tracking-wider text-muted-foreground pt-2 first:pt-0">
              {trimmed.replace(/^#+\s*/, '')}
            </h4>
          );
        }
        if (trimmed.startsWith('# ')) {
          return (
            <h3 key={i} className="text-sm font-bold text-foreground pt-2 first:pt-0">
              {trimmed.replace(/^#+\s*/, '')}
            </h3>
          );
        }

        if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
          const content = trimmed.slice(2);
          return (
            <div key={i} className="flex gap-2">
              <span className="text-muted-foreground mt-0.5 flex-shrink-0">•</span>
              <span dangerouslySetInnerHTML={{ __html: formatInline(content) }} />
            </div>
          );
        }

        if (!trimmed) return <div key={i} className="h-1" />;

        return (
          <p key={i} dangerouslySetInnerHTML={{ __html: formatInline(trimmed) }} />
        );
      })}
    </div>
  );
};

/**
 * Splits a multi-line warnings/strengths string into a list of items.
 * Backend may emit bullet markers ("-", "*", "•") or one-per-line plain text.
 */
const splitItems = (text: string | undefined | null, max?: number): string[] => {
  if (!text) return [];
  const lines = text
    .split(/\r?\n+/)
    .map(l => l.replace(/^\s*[-*•]\s*/, '').trim())
    .filter(l => l.length > 0);
  return typeof max === 'number' ? lines.slice(0, max) : lines;
};

interface BriefingCardProps {
  accountId?: string;
  /** Layout variant. 'full' (default) renders the full briefing; 'compact' renders a banner with the first 2 warnings + 2 strengths and a CTA. */
  variant?: 'full' | 'compact';
}

const BriefingCard: React.FC<BriefingCardProps> = ({ accountId, variant = 'full' }) => {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const { data: briefing, isLoading } = useBriefing(accountId);
  const { mutate: generate, isPending: isGenerating } = useGenerateBriefing(accountId);

  // ---------------- Compact variant ----------------
  if (variant === 'compact') {
    if (isLoading) {
      return (
        <div data-testid="briefing-compact-skeleton" className="rounded-xl border border-border/60 bg-card/50 p-4 space-y-2">
          <Skeleton className="h-4 w-1/3" />
          <Skeleton className="h-3 w-full" />
          <Skeleton className="h-3 w-5/6" />
        </div>
      );
    }

    if (!briefing) {
      // No briefing yet — render nothing in compact mode (Dashboard hides the banner)
      return null;
    }

    const warningItems = splitItems(briefing.warnings, 2);
    const strengthItems = splitItems(briefing.strengths, 2);

    return (
      <div
        data-testid="briefing-compact"
        className={cn(
          'group relative rounded-xl border border-amber-200/50 dark:border-amber-800/40',
          'bg-gradient-to-br from-amber-50/70 via-card to-card dark:from-amber-950/20 dark:via-card dark:to-card',
          'p-4 transition-shadow duration-200 hover:shadow-md',
        )}
      >
        <div className="flex items-start justify-between gap-4">
          <div className="flex items-center gap-2 min-w-0">
            <Sparkles className="h-4 w-4 text-amber-500 flex-shrink-0" />
            <div className="flex flex-col">
              <h3 className="text-sm font-semibold text-foreground">
                {t('ai.morningBriefing', 'Morning Briefing')}
              </h3>
              <span className="text-[11px] text-muted-foreground font-mono tabular-nums">
                {new Date(briefing.briefingDate).toLocaleDateString()}
              </span>
            </div>
          </div>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate('/ai-coach')}
            className="h-7 text-xs gap-1 text-amber-700 dark:text-amber-400 hover:text-amber-900 dark:hover:text-amber-300"
          >
            {t('aiCoach.briefingCard.viewDetails', 'View full briefing')}
            <ArrowRight className="h-3.5 w-3.5" />
          </Button>
        </div>

        {(warningItems.length > 0 || strengthItems.length > 0) && (
          <div className="mt-3 grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
            {warningItems.length > 0 && (
              <div className="space-y-1">
                <span className="text-[10px] font-semibold uppercase tracking-wider text-amber-700 dark:text-amber-400">
                  {t('ai.debriefImprovements', 'Warnings')}
                </span>
                <ul className="space-y-1">
                  {warningItems.map((item, i) => (
                    <li key={i} className="flex gap-1.5 text-muted-foreground">
                      <span className="text-amber-500 mt-0.5">•</span>
                      <span className="line-clamp-2">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
            {strengthItems.length > 0 && (
              <div className="space-y-1">
                <span className="text-[10px] font-semibold uppercase tracking-wider text-emerald-700 dark:text-emerald-400">
                  {t('ai.debriefStrengths', 'Strengths')}
                </span>
                <ul className="space-y-1">
                  {strengthItems.map((item, i) => (
                    <li key={i} className="flex gap-1.5 text-muted-foreground">
                      <span className="text-emerald-500 mt-0.5">•</span>
                      <span className="line-clamp-2">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}
      </div>
    );
  }

  // ---------------- Full variant (unchanged behavior) ----------------
  if (isLoading) {
    return (
      <div className="space-y-3">
        <Skeleton className="h-4 w-full" />
        <Skeleton className="h-4 w-5/6" />
        <Skeleton className="h-4 w-4/6" />
      </div>
    );
  }

  return (
    <div className="space-y-3">
      {/* Header — date + generate button */}
      <div className="flex items-center justify-between">
        {briefing ? (
          <span className="text-xs text-muted-foreground font-mono tabular-nums">
            {new Date(briefing.briefingDate).toLocaleDateString()}
          </span>
        ) : (
          <span />
        )}
        <Button
          variant="ghost"
          size="sm"
          onClick={() => generate()}
          disabled={isGenerating}
          className="h-7 text-xs gap-1.5"
        >
          {isGenerating ? (
            <Loader2 className="h-3.5 w-3.5 animate-spin" />
          ) : (
            <RefreshCw className="h-3.5 w-3.5" />
          )}
          {briefing ? t('ai.regenerate') : t('ai.generateBtn')}
        </Button>
      </div>

      {/* Content */}
      {briefing ? (
        <div className="space-y-3">
          <SimpleMarkdown text={briefing.content} />
          {briefing.warnings && (
            <div className="flex gap-2 p-3 bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-lg">
              <AlertCircle className="h-4 w-4 text-amber-600 dark:text-amber-400 flex-shrink-0 mt-0.5" />
              <div className="text-xs text-amber-800 dark:text-amber-200">
                <strong>Warnings:</strong> {briefing.warnings}
              </div>
            </div>
          )}
        </div>
      ) : (
        <div className="text-center py-4">
          <p className="text-xs text-muted-foreground">
            {t('ai.briefingEmpty')}
          </p>
        </div>
      )}
    </div>
  );
};

export default BriefingCard;
